<%

Session("RanNo") = ""
Session("Regisno") = ""
Session("EmpID") = ""
Session("EmpName") = ""
Session("Responsibility")=""
Session("ConnectStr") = ""
Session("CurrentDate") = ""
Session("ssLeavetypeid") = ""
Session("ssDate1") = ""
Session("ssDate2") = ""
Session("ssDate1att") = ""
Session("ssDate2att") = ""
Session("ssStatus") = ""
Session("ssSearchBy")=""
Session("ssID")=""
Session("ssDate1lv")=""
Session("ssDate2lv")=""
Session("sscboempidlv")=""
Session("ssempiderror")=""
Session("sserrorerror")=""
Session("ssdate1error")=""
Session("ssdate2error")=""
session("ssyear") = ""
session("sssel") = ""
Session("organname") =""

Session("HomePage")="http://SSDCSWPDB416/ehres/main.asp"
%>
